drop table USER if exists

-- Tables
create table USER (id bigint generated by default as identity (start with 1), user_name  varchar(20), last_name varchar(255), first_name varchar(100), primary key (id))

-- Data
insert into USER (user_name, last_name,first_name) values ('brojo', 'Brouwers','Jozef')
insert into USER (user_name, last_name,first_name) values ('arnwi', 'Arnouts','Wim')
insert into USER (user_name, last_name,first_name) values ('alast', 'Alaerts','Stefan')